//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseControlNet.VisualStudio
{
    using System;

    /// <summary>
    /// The identifiers from the command table.
    /// </summary>
	public static class CommandTableIdentifiers
	{
        /// <summary>
        /// ID value for menuMain.
        /// </summary>
		public const uint menuMain = 0x1001;

        /// <summary>
        /// ID value for menuMonitor.
        /// </summary>
		public const uint menuMonitor = 0x1002;

        /// <summary>
        /// ID value for groupMain.
        /// </summary>
		public const uint groupMain = 0x2001;

        /// <summary>
        /// ID value for groupWindows.
        /// </summary>
		public const uint groupWindows = 0x2002;

        /// <summary>
        /// ID value for groupSettings.
        /// </summary>
		public const uint groupSettings = 0x2003;

        /// <summary>
        /// ID value for groupMonitor1.
        /// </summary>
		public const uint groupMonitor1 = 0x2004;

        /// <summary>
        /// ID value for groupMonitor2.
        /// </summary>
		public const uint groupMonitor2 = 0x2005;

        /// <summary>
        /// ID value for cmdSettings.
        /// </summary>
		public const uint cmdSettings = 0x3001;

        /// <summary>
        /// ID value for cmdMonitorWindow.
        /// </summary>
		public const uint cmdMonitorWindow = 0x3002;

        /// <summary>
        /// ID value for cmdForceProject.
        /// </summary>
		public const uint cmdForceProject = 0x3003;

        /// <summary>
        /// ID value for cmdAbortProject.
        /// </summary>
		public const uint cmdAbortProject = 0x3004;

        /// <summary>
        /// ID value for cmdStartProject.
        /// </summary>
		public const uint cmdStartProject = 0x3005;

        /// <summary>
        /// ID value for cmdStopProject.
        /// </summary>
		public const uint cmdStopProject = 0x3006;

        /// <summary>
        /// ID value for bmpMonitor.
        /// </summary>
		public const uint bmpMonitor = 1;

        /// <summary>
        /// ID value for bmpSettings.
        /// </summary>
		public const uint bmpSettings = 2;

        /// <summary>
        /// ID value for bmpForceProject.
        /// </summary>
		public const uint bmpForceProject = 3;

        /// <summary>
        /// ID value for bmpAbortProject.
        /// </summary>
		public const uint bmpAbortProject = 4;

        /// <summary>
        /// ID value for bmpStartProject.
        /// </summary>
		public const uint bmpStartProject = 5;

        /// <summary>
        /// ID value for bmpStopProject.
        /// </summary>
		public const uint bmpStopProject = 6;

	}

    /// <summary>
    /// The strings from the command table.
    /// </summary>
	public static class CommandTableStrings
	{
        /// <summary>
        /// ID value for guidCruiseControlNetPackage.
        /// </summary>
		public const string guidCruiseControlNetPackage = "c9d6fe21-b2be-4c41-8e88-52f73b15537c";

        /// <summary>
        /// ID value for guidCruiseControlNetCmdSet.
        /// </summary>
		public const string guidCruiseControlNetCmdSet = "b4637b2e-c070-467f-a327-1bf0eccfad5b";

        /// <summary>
        /// ID value for guidImages.
        /// </summary>
		public const string guidImages = "6053699b-8e2a-47ed-983f-e7ae2abb3271";

	}

    /// <summary>
    /// The GUIDs from the command table.
    /// </summary>
	public static class CommandTableGuids
	{
        /// <summary>
        /// ID value for guidCruiseControlNetPackage.
        /// </summary>
		public static readonly Guid guidCruiseControlNetPackage = new Guid(CommandTableStrings.guidCruiseControlNetPackage);

        /// <summary>
        /// ID value for guidCruiseControlNetCmdSet.
        /// </summary>
		public static readonly Guid guidCruiseControlNetCmdSet = new Guid(CommandTableStrings.guidCruiseControlNetCmdSet);

        /// <summary>
        /// ID value for guidImages.
        /// </summary>
		public static readonly Guid guidImages = new Guid(CommandTableStrings.guidImages);

	}
}
